import Accordion from "@/components/Accordion";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
  const [activeIndex, setActiveIndex] = useState(null);

  const arrayProblems = [
    {
      title: "Contains Duplicate",
      url: "https://leetcode.com/problems/contains-duplicate/",
    },
    {
      title: "Valid Anagram",
      url: "https://leetcode.com/problems/valid-anagram/",
    },
  ];

  return (
    <>
      <Head>
        <title>Fallen Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Fallen Code</div>

        <div>Calendar</div>

        <div>
          <ul>
            <li>Arrays</li>
            <Accordion items={arrayProblems} />
          </ul>
        </div>
      </main>
    </>
  );
}
