import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fallen Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Fallen Code</div>

        <div>Calendar</div>

        <div>
          <ul>
            <li>Arrays & Hashing</li>
          </ul>
        </div>
      </main>
    </>
  );
}
